CREATE TYPE "SurveyStatus" AS ENUM ('DRAFT','ACTIVE','PAUSED','STOPPED');
CREATE TYPE "QuestionType" AS ENUM ('TEXT','TEXTAREA','SINGLE_CHOICE','MULTIPLE_CHOICE','SELECT','RATING','DATE','NUMBER');
CREATE TABLE "User" ("id" TEXT PRIMARY KEY,"username" TEXT NOT NULL UNIQUE,"passwordHash" TEXT NOT NULL,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Role" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL UNIQUE,"description" TEXT);
CREATE TABLE "Permission" ("id" TEXT PRIMARY KEY,"key" TEXT NOT NULL UNIQUE,"description" TEXT NOT NULL);
CREATE TABLE "UserRole" ("userId" TEXT NOT NULL,"roleId" TEXT NOT NULL,PRIMARY KEY("userId","roleId"));
CREATE TABLE "RolePermission" ("roleId" TEXT NOT NULL,"permissionId" TEXT NOT NULL,PRIMARY KEY("roleId","permissionId"));
CREATE TABLE "Survey" ("id" TEXT PRIMARY KEY,"slug" TEXT NOT NULL UNIQUE,"title" TEXT NOT NULL,"description" TEXT,"status" "SurveyStatus" NOT NULL DEFAULT 'DRAFT',"allowAnonymous" BOOLEAN NOT NULL DEFAULT true,"requireLogin" BOOLEAN NOT NULL DEFAULT false,"restrictDevice" BOOLEAN NOT NULL DEFAULT false,"restrictIp" BOOLEAN NOT NULL DEFAULT false,"maxSubmissions" INTEGER NOT NULL DEFAULT 1,"showProgress" BOOLEAN NOT NULL DEFAULT true,"showQuestionNumber" BOOLEAN NOT NULL DEFAULT true,"startsAt" TIMESTAMP(3),"endsAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"ownerId" TEXT NOT NULL);
CREATE TABLE "SurveyQuestion" ("id" TEXT PRIMARY KEY,"surveyId" TEXT NOT NULL,"order" INTEGER NOT NULL,"type" "QuestionType" NOT NULL,"title" TEXT NOT NULL,"description" TEXT,"required" BOOLEAN NOT NULL DEFAULT false,"config" JSONB NOT NULL);
CREATE TABLE "SurveyLogicRule" ("id" TEXT PRIMARY KEY,"surveyId" TEXT NOT NULL,"sourceQuestionId" TEXT NOT NULL,"targetQuestionId" TEXT NOT NULL,"operator" TEXT NOT NULL,"value" JSONB NOT NULL,"action" TEXT NOT NULL);
CREATE TABLE "SurveyResponse" ("id" TEXT PRIMARY KEY,"surveyId" TEXT NOT NULL,"respondentId" TEXT,"ipHash" TEXT,"deviceHash" TEXT,"status" TEXT NOT NULL DEFAULT 'COMPLETED',"startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"completedAt" TIMESTAMP(3));
CREATE TABLE "SurveyAnswer" ("id" TEXT PRIMARY KEY,"responseId" TEXT NOT NULL,"questionId" TEXT NOT NULL,"value" JSONB NOT NULL);
CREATE TABLE "SurveyEvent" ("id" TEXT PRIMARY KEY,"surveyId" TEXT NOT NULL,"type" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "SurveyQuestion_surveyId_order_idx" ON "SurveyQuestion"("surveyId","order");
CREATE INDEX "SurveyResponse_surveyId_completedAt_idx" ON "SurveyResponse"("surveyId","completedAt");
CREATE UNIQUE INDEX "SurveyAnswer_responseId_questionId_key" ON "SurveyAnswer"("responseId","questionId");
CREATE INDEX "SurveyEvent_surveyId_createdAt_idx" ON "SurveyEvent"("surveyId","createdAt");
ALTER TABLE "UserRole" ADD CONSTRAINT "UserRole_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UserRole" ADD CONSTRAINT "UserRole_roleId_fkey" FOREIGN KEY("roleId") REFERENCES "Role"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RolePermission" ADD CONSTRAINT "RolePermission_roleId_fkey" FOREIGN KEY("roleId") REFERENCES "Role"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RolePermission" ADD CONSTRAINT "RolePermission_permissionId_fkey" FOREIGN KEY("permissionId") REFERENCES "Permission"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Survey" ADD CONSTRAINT "Survey_ownerId_fkey" FOREIGN KEY("ownerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveyQuestion" ADD CONSTRAINT "SurveyQuestion_surveyId_fkey" FOREIGN KEY("surveyId") REFERENCES "Survey"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveyLogicRule" ADD CONSTRAINT "SurveyLogicRule_surveyId_fkey" FOREIGN KEY("surveyId") REFERENCES "Survey"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveyLogicRule" ADD CONSTRAINT "SurveyLogicRule_targetQuestionId_fkey" FOREIGN KEY("targetQuestionId") REFERENCES "SurveyQuestion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveyResponse" ADD CONSTRAINT "SurveyResponse_surveyId_fkey" FOREIGN KEY("surveyId") REFERENCES "Survey"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveyResponse" ADD CONSTRAINT "SurveyResponse_respondentId_fkey" FOREIGN KEY("respondentId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SurveyAnswer" ADD CONSTRAINT "SurveyAnswer_responseId_fkey" FOREIGN KEY("responseId") REFERENCES "SurveyResponse"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveyAnswer" ADD CONSTRAINT "SurveyAnswer_questionId_fkey" FOREIGN KEY("questionId") REFERENCES "SurveyQuestion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveyEvent" ADD CONSTRAINT "SurveyEvent_surveyId_fkey" FOREIGN KEY("surveyId") REFERENCES "Survey"("id") ON DELETE CASCADE ON UPDATE CASCADE;
